first
FreeCourseJava/FFF_homeworks pull request #1
Opened 2022-06-13 23:00 UTC by tru10b

2022-06-14 08:28 UTC, ivtcro reviewed
ok

2022-06-15 14:09 UTC, hyragano requested changes

2022-06-15 14:09 UTC, hyragano commented on src/main/java/main.java
> +        return deposit+income;
что будет если  баланс будет равен 2147470000 и income 110000 ?

2022-06-15 14:09 UTC, hyragano commented on src/main/java/main.java
> +    public static void char_convert(char init_char, int offset)
названия методов в camelCase

2022-06-15 14:09 UTC, hyragano commented on src/main/java/main.java
> +    public static void sheep_count (int count)
названия методов в camelCase

2022-06-15 15:37 UTC, tru10b commented on src/main/java/main.java
> +        return deposit+income;
будет то самое переполнение, произойдет переход в область отрицательных значений, отсчитываемых от минимально возможного значения типа инт

2022-06-15 15:38 UTC, tru10b commented on src/main/java/main.java
> +    public static void char_convert(char init_char, int offset)
исправил, сделал второй комит

2022-06-15 15:38 UTC, tru10b commented on src/main/java/main.java
> +    public static void sheep_count (int count)
исправил, сделал второй комит

2022-06-20 14:55 UTC, hyragano approved these changes

2022-06-20 17:03 UTC, merged