Second exercise
FreeCourseJava/FFF_homeworks pull request #2
Opened 2022-06-19 19:46 UTC by tru10b

Второе домашнее задание

2022-06-20 08:41 UTC, ivtcro commented on src/main/java/second_exercise.java
> +        return flag ? sum : 0;
флаг лучше обозвать как-то осмысленно, типа isOverflow

2022-06-20 08:41 UTC, ivtcro commented on src/main/java/second_exercise.java
> +        private static long daysToMsecFromNow(long days) {
а если days=Long.MAX_VALUE?

2022-06-20 10:49 UTC, tru10b commented on src/main/java/second_exercise.java
> +        return flag ? sum : 0;
принято

2022-06-20 10:50 UTC, tru10b commented on src/main/java/second_exercise.java
> +        private static long daysToMsecFromNow(long days) {
добавил проверку на переполнение

2022-06-20 14:58 UTC, hyragano requested changes

2022-06-20 14:58 UTC, hyragano commented on src/main/java/second_exercise.java
> +        if (deposit > 0 & income > 0 & sum < 0) isOwerflow = false;
Бинарная проверка? Лучше уж && использовать, но пока без этого делаем, попробуй подумать над решением. 
Подсказка: кастинг поможет нам

2022-06-20 14:58 UTC, hyragano commented on src/main/java/second_exercise.java
> +        long overFlawCrit=(Long.MAX_VALUE-System.currentTimeMillis())/(24L * 60L * 60L * 1000L);
красавчик есть же. Только все в лонги можно не пихать. и да, days можно делать int-ом, так как гадостный расклад ты преодолел

2022-06-20 17:27 UTC, tru10b commented on src/main/java/second_exercise.java
> +        if (deposit > 0 & income > 0 & sum < 0) isOwerflow = false;
переписал метод с использованием приведения типов

2022-06-20 17:28 UTC, tru10b commented on src/main/java/second_exercise.java
> +        long overFlawCrit=(Long.MAX_VALUE-System.currentTimeMillis())/(24L * 60L * 60L * 1000L);
я так понимаю, исправлять не надо?)

2022-06-20 17:31 UTC, hyragano approved these changes

2022-06-20 17:32 UTC, hyragano requested changes

2022-06-20 17:32 UTC, hyragano commented on src/main/java/second_exercise.java
> +        long overFlawCrit=(Long.MAX_VALUE-System.currentTimeMillis())/(24L * 60L * 60L * 1000L);
для чего вычитаем из максвэлью?

2022-06-20 17:32 UTC, hyragano commented on src/main/java/second_exercise.java
> +        long timeInMS = System.currentTimeMillis() + days * 24L * 60L * 60L * 1000L;
для чего прибавляем к макс вэлью?

2022-06-20 17:42 UTC, tru10b commented on src/main/java/second_exercise.java
> +        long overFlawCrit=(Long.MAX_VALUE-System.currentTimeMillis())/(24L * 60L * 60L * 1000L);
я попытался защитить переменную timeInMS от переполнения в случае добавления бешеного количества дней
для этого я взял максимально возможное значение, изьял из него уже прошедшие до момента вызова функции миллисекунды, а затем привел к числу дней. Это число дает максимальное число дней, которое еще не переполняет искомую переменную

2022-06-20 17:42 UTC, tru10b commented on src/main/java/second_exercise.java
> +        long timeInMS = System.currentTimeMillis() + days * 24L * 60L * 60L * 1000L;
?

2022-06-20 17:45 UTC, hyragano commented on src/main/java/second_exercise.java
> +        long timeInMS = System.currentTimeMillis() + days * 24L * 60L * 60L * 1000L;
Не. Тут норм. я тупанул

2022-06-20 17:50 UTC, hyragano requested changes

2022-06-20 17:50 UTC, hyragano commented on src/main/java/second_exercise.java
> +        long overFlawCrit=(Long.MAX_VALUE-System.currentTimeMillis())/(24L * 60L * 60L * 1000L);
Long.MAX_VALUE-System.currentTimeMillis() 
поясни плз, для чего вот это?

2022-06-20 17:50 UTC, hyragano commented on src/main/java/second_exercise.java
> +        long overFlawCrit=(Long.MAX_VALUE-System.currentTimeMillis())/(24L * 60L * 60L * 1000L);
Это уже не нужно, если какой-то чудак захочет добавить столько дней, чтобы long переполнился, то это уже не наши проблемы

2022-06-20 17:50 UTC, hyragano commented on src/main/java/second_exercise.java
> +        long overFlawCrit=(Long.MAX_VALUE-System.currentTimeMillis())/(24L * 60L * 60L * 1000L);
Но голову разрабам взорвет прилично

2022-06-20 17:50 UTC, hyragano commented on src/main/java/second_exercise.java
> +        if (Math.abs((long)deposit+(long)income)>Integer.MAX_VALUE) isOwerflow = false;
Это решение 2-го или сразу и 3-го задания?
если 3, то получается если у нас балансу с минусом прилетит минсовой инком, то будет сюрприз и должник станет богатым чуваком?

2022-06-20 17:51 UTC, hyragano commented on src/main/java/second_exercise.java
> +        if (Math.abs((long)deposit+(long)income)>Integer.MAX_VALUE) isOwerflow = false;
тут с одной стороны проще, с другой сложнее. мы не изучали еще методы стандартной JDK, я понимаю, что ты с ними или знаком или находишь, НО тут решение без них.
Попробуй подумать дальше про каст.

2022-06-20 18:24 UTC, tru10b commented on src/main/java/second_exercise.java
> +        long overFlawCrit=(Long.MAX_VALUE-System.currentTimeMillis())/(24L * 60L * 60L * 1000L);
переписал метод, чтобы на вход брал инт.
тогда лонг точно не переполнится и никаких защит-проверок не надо

2022-06-20 18:24 UTC, tru10b commented on src/main/java/second_exercise.java
> +        if (Math.abs((long)deposit+(long)income)>Integer.MAX_VALUE) isOwerflow = false;
и 2 и 3 задание, там же речь об одном и том же
насчет минусовых балансов - так не будет, проверка на переполнение идет по модулю, а на выход дается честная сумма

2022-06-20 18:25 UTC, tru10b commented on src/main/java/second_exercise.java
> +        long overFlawCrit=(Long.MAX_VALUE-System.currentTimeMillis())/(24L * 60L * 60L * 1000L);
это все было для борьбы с переполнением лонга
но теперь метод переписал,чтобы этот вопрос вообще не возникал)

2022-06-20 18:27 UTC, tru10b commented on src/main/java/second_exercise.java
> +        if (Math.abs((long)deposit+(long)income)>Integer.MAX_VALUE) isOwerflow = false;
переписал метод
теперь сразу расширяю в лонг аргументы метода и беру их сумму в лонг, она тчно не переполнится.
Затем эту лонговую сумму сравниваю с экстремальными значеняими инта, и в зависмости от этого выставляю ьулевый флаг
на возврат из метода даю либо ноль либо честную интовую сумму

2022-06-20 18:39 UTC, hyragano requested changes

2022-06-20 18:39 UTC, hyragano commented on src/main/java/second_exercise.java
> +        if ((sum>Integer.MAX_VALUE) || (sum < Integer.MIN_VALUE)) isOwerflow = false;
В принципе да, Но мы еще || не знаем. Далее можно еще подумать и до ума довести без || и прочей нечести

2022-06-20 18:39 UTC, hyragano commented on src/main/java/second_exercise.java
> +        return isOwerflow ? (deposit + income) : 0;
выкинь, плз, тернарный оператор, не дай боже кто-то увидит его

2022-06-20 18:44 UTC, blekkiw commented on src/main/java/second_exercise.java
> +public class second_exercise {
Название класа не соответствует java стандарту. Как говорил Алексей - нужен CamelCase. В твоем случае имя класса и файла должно быть SecondExercise

2022-06-20 18:44 UTC, blekkiw commented on src/main/java/second_exercise.java
> +        if ((sum>Integer.MAX_VALUE) || (sum < Integer.MIN_VALUE)) isOwerflow = false;
Определись, или ставишь пробелы между знаками, или нет

2022-06-20 18:44 UTC, blekkiw commented on src/main/java/second_exercise.java
> +        if ((sum>Integer.MAX_VALUE) || (sum < Integer.MIN_VALUE)) isOwerflow = false;
Вообще странное использование ифа для складывания в переменную. Можно же сразу в переменную положить то, что внутри круглых скобок ифа? Ну либо вообще отказаться от переменной, и делать return внутри ифа. А то как-то наворочено получается, учитывая что дальше следует тернарка.

2022-06-20 18:55 UTC, tru10b commented on src/main/java/second_exercise.java
> +        if ((sum>Integer.MAX_VALUE) || (sum < Integer.MIN_VALUE)) isOwerflow = false;
переписал через два ифа

2022-06-20 18:56 UTC, tru10b commented on src/main/java/second_exercise.java
> +        return isOwerflow ? (deposit + income) : 0;
выполнил

2022-06-20 18:56 UTC, tru10b commented on src/main/java/second_exercise.java
> +public class second_exercise {
исправил

2022-06-20 18:56 UTC, tru10b commented on src/main/java/second_exercise.java
> +        if ((sum>Integer.MAX_VALUE) || (sum < Integer.MIN_VALUE)) isOwerflow = false;
забабахал автоформатирование

2022-06-20 18:57 UTC, tru10b commented on src/main/java/second_exercise.java
> +        if ((sum>Integer.MAX_VALUE) || (sum < Integer.MIN_VALUE)) isOwerflow = false;
переписал всю конструкцию

2022-06-20 19:02 UTC, blekkiw requested changes

2022-06-20 19:02 UTC, blekkiw commented on src/main/java/SecondExercise.java
> +        if (sum > Integer.MAX_VALUE) return 0;
Даже если после if или else одно выражение - стоит писать его в фигурных скобках

2022-06-20 19:07 UTC, tru10b commented on src/main/java/SecondExercise.java
> +        if (sum > Integer.MAX_VALUE) return 0;
исправил

2022-06-20 19:20 UTC, blekkiw approved these changes

2022-06-21 11:11 UTC, hyragano requested changes

2022-06-21 11:11 UTC, hyragano commented on src/main/java/SecondExercise.java
> +        if (sum > Integer.MAX_VALUE) {
Норм, но можно без этого. Подумай в сторону кастинга ещё раз. Поиграйся с кастингом результата сложения интов и результатом кастнутых интов...

2022-06-21 19:50 UTC, tru10b commented on src/main/java/SecondExercise.java
> +        if (sum > Integer.MAX_VALUE) {
переписал метод через сравнение кастнутой лонг суммы и исходной интовой суммой

2022-06-22 04:10 UTC, hyragano approved these changes

2022-06-22 04:36 UTC, merged