initial commit
FreeCourseJava/FFF_homeworks pull request #3
Opened 2022-07-01 22:57 UTC by tru10b

Третье домашнее задание, все три задачи в одном ява-классе

2022-07-02 11:44 UTC, eebelyaev requested changes

2022-07-02 11:44 UTC, eebelyaev commented on src/main/java/ThirdExercise.java
> +        for (int j = 0; j < massiv.length; j++) {
Тут можно лучше

2022-07-02 11:44 UTC, eebelyaev commented on src/main/java/ThirdExercise.java
> +    }
Попробуй найти значение 1852 в массиве [1801, 1851, 1876, 1886, 1896, 1901, 1906, 1907, 1911, 1913, 1916, 1921, 1926, 1931, 1936, 1956, 1961, 1966, 1976, 1996]

2022-07-02 14:15 UTC, hyragano commented on src/main/java/ThirdExercise.java
> +        for (int j = 0; j < massiv.length; j++) {
> Тут можно лучше

Поясни чуть конкретнее, что предлагаешь улучшить

2022-07-02 14:33 UTC, hyragano requested changes

2022-07-02 14:33 UTC, hyragano commented on src/main/java/ThirdExercise.java
> +    public static boolean binarySearch(int[] massiv, int value) {
по-красоте лучше не юзать транслит, лучше названия на англ,

2022-07-02 18:12 UTC, eebelyaev commented on src/main/java/ThirdExercise.java
> +        for (int j = 0; j < massiv.length; j++) {
Специально не сказал, чтоб поразгадывать ))
Здесь делается одна лишняя проверка.
Нужно уменьшить диапазон верхнего счётчика.

2022-07-02 21:55 UTC, tru10b commented on src/main/java/ThirdExercise.java
> +        for (int j = 0; j < massiv.length; j++) {
исправил

2022-07-02 21:55 UTC, tru10b commented on src/main/java/ThirdExercise.java
> +    }
переписал алгоритм, добавил указанную проверку

2022-07-02 21:56 UTC, tru10b commented on src/main/java/ThirdExercise.java
> +    public static boolean binarySearch(int[] massiv, int value) {
исправил

2022-07-04 14:00 UTC, blekkiw requested changes

2022-07-04 14:00 UTC, blekkiw commented on src/main/java/ThirdExercise.java
> +        for (int i = 1; i <= size; i++) {
Вроде как логичнее и понятнее будет считать с 0, и не делать тогда [i -1]

2022-07-04 14:00 UTC, blekkiw commented on src/main/java/ThirdExercise.java
> +        for (int j = 0; j < (array.length - 1); j++) {
Тут то же, но веселее. Подумай, может можно упростить? А то вот это вот - j -1 +1 вообще не очень читаемо

2022-07-04 14:00 UTC, blekkiw commented on src/main/java/ThirdExercise.java
> +        for (; ; ) {
Так работает. Правда если длина массива = 0, то падает.

2022-07-04 17:37 UTC, tru10b commented on src/main/java/ThirdExercise.java
> +        for (; ; ) {
добавил проверку

2022-07-04 17:38 UTC, tru10b commented on src/main/java/ThirdExercise.java
> +        for (int i = 1; i <= size; i++) {
исправил
хотел обойти дление на ноль в заполнение массива, добавил дополнительное условие

2022-07-04 17:39 UTC, tru10b commented on src/main/java/ThirdExercise.java
> +        for (int j = 0; j < (array.length - 1); j++) {
ввел перемнную для максимального индекса массива

2022-07-04 18:32 UTC, blekkiw requested changes

2022-07-04 18:32 UTC, blekkiw commented on src/main/java/ThirdExercise.java
> +        int[] NullArray = new int[0];
Названия переменных с маленькой буквы

2022-07-04 18:35 UTC, tru10b commented on src/main/java/ThirdExercise.java
> +        int[] NullArray = new int[0];
исправил

2022-07-04 18:38 UTC, blekkiw approved these changes

2022-07-05 19:15 UTC, hyragano approved these changes

2022-07-05 19:16 UTC, merged