Fourth exercise
FreeCourseJava/FFF_homeworks pull request #4
Opened 2022-07-08 21:13 UTC by tru10b

В классе по домашнему заданию четвертого занятия имеются два метода:

private static int[] cocktailShakerSort(int[] array) - это сортировка шейкерным методом

private static boolean binarySearchRecursive(int[] array, int value) - это бинарный поиск с применение рекурсии и копирования массива

2022-07-08 21:43 UTC, eebelyaev commented on src/main/java/FourthExercise.java
> +        if (array.length == 0 || array.length == 1) {
Лучше array.length < 2

2022-07-09 05:45 UTC, tru10b commented on src/main/java/FourthExercise.java
> +        if (array.length == 0 || array.length == 1) {
согласен, исправил

2022-07-09 16:42 UTC, hyragano requested changes

2022-07-09 16:42 UTC, hyragano commented on src/main/java/FourthExercise.java
> +            for (int i = 0; i < bound; i++) {
Разве нужны коктейль шейкеру вложенные циклы?

2022-07-09 18:16 UTC, hyragano commented on src/main/java/FourthExercise.java
> +            for (int i = 0; i < bound; i++) {
Моя ошибка. Нужны

2022-07-09 18:17 UTC, hyragano approved these changes

2022-07-13 13:44 UTC, blekkiw approved these changes

2022-07-13 20:13 UTC, merged