Fifth exercise
FreeCourseJava/FFF_homeworks pull request #5
Opened 2022-07-16 21:52 UTC by tru10b

Каждый класс отдельным файлом

2022-07-18 19:16 UTC, hyragano requested changes

2022-07-18 19:16 UTC, hyragano commented on src/main/java/House.java
> +    int area;
Тут вроде 2 параметра должно быть

2022-07-18 19:16 UTC, hyragano commented on src/main/java/House.java
> +    public House() {
Дефолтный возможно стоит убрать

2022-07-18 19:16 UTC, hyragano commented on src/main/java/Park.java
> +    int area;
2 параметра

2022-07-19 13:13 UTC, tru10b commented on src/main/java/House.java
> +    int area;
исправил

2022-07-19 13:13 UTC, tru10b commented on src/main/java/Park.java
> +    int area;
исправил

2022-07-19 13:13 UTC, tru10b commented on src/main/java/House.java
> +    public House() {
убрал

2022-08-08 20:03 UTC, hyragano approved these changes

2022-08-09 06:40 UTC, blekkiw requested changes

2022-08-09 06:40 UTC, blekkiw commented on src/main/java/fifth/City.java
> +    public void addStreet(String name, int kadastrNumber, int length, int meanWidth,
Не проще ли сверху подвать объект Street? 1 аргумент лучше7

2022-08-09 06:40 UTC, blekkiw commented on src/main/java/fifth/Street.java
> +    public void addHouse(int number, int length, int width) {
Такая же ерунда. Подай один объект вместо трех

2022-08-09 07:35 UTC, tru10b commented on src/main/java/fifth/City.java
> +    public void addStreet(String name, int kadastrNumber, int length, int meanWidth,
я хотел вызывать конструктор внутри метода, а так придется конструктор бахать перед применением метода
но конечно 1 аргумент гламурней 7, так что исправил

2022-08-09 07:35 UTC, tru10b commented on src/main/java/fifth/Street.java
> +    public void addHouse(int number, int length, int width) {
исправил

2022-08-10 07:45 UTC, blekkiw requested changes

2022-08-10 07:45 UTC, blekkiw commented on src/main/java/fifth/Street.java
> +        this.houses = houses;
Если ты сделал специальные методы для добавления, может и не стоит подавать в контсруктор массивы?

2022-08-10 07:45 UTC, blekkiw commented on src/main/java/fifth/Street.java
> +    int kadastrNumber;
Если ты закрыл от других свою логику заполнения, может стоит тут сделать private?

2022-08-12 09:22 UTC, tru10b commented on src/main/java/fifth/Street.java
> +        this.houses = houses;
убрал массивы из конструкторов

2022-08-12 09:30 UTC, tru10b commented on src/main/java/fifth/Street.java
> +    int kadastrNumber;
закрыл поля в классах домов, парков, улиц и городов
доступ к ним при необходимости сделаю через методы в следующих заданиях

2022-08-12 11:33 UTC, tru10b commented
я опять не успел замержить ветку, так что новое задание выполняю в ветке от пятого задания
внес правки в методы, теперь динамический массив - это отдельный класс, добавил наследование, учел все предыдущие замечния

2022-08-15 10:08 UTC, blekkiw requested changes

2022-08-15 10:08 UTC, blekkiw commented on src/main/java/fifth/ArrayExtended.java
> +    private Object[] current = null;
Можно и так конечно. Но суть была в том, чтобы сделать поле типа measurable, тогда тебе не надо будет делать каст House temp = (House) this.houses.getFromArray(i);

2022-08-16 20:53 UTC, tru10b commented on src/main/java/fifth/ArrayExtended.java
> +    private Object[] current = null;
исправил
но остается каст для улиц, когда в классе city я делаю метод для подсчета домов. там мне нужно обращаться к методу, определенному в street,  а не measureable

2022-08-19 08:22 UTC, blekkiw approved these changes

2022-08-19 20:55 UTC, merged