init commit
FreeCourseJava/FFF_homeworks pull request #6
Opened 2022-08-26 10:26 UTC by tru10b

ninth package

2022-08-26 14:23 UTC, blekkiw requested changes
Еще желательно начинать более осознанно называть коммиты и пулл реквесты. А то уже 10 занятие, а у тебя все inital

2022-08-26 14:23 UTC, blekkiw commented on src/main/java/ninth/IntArrayUtils.java
> +
Добавь приватный конструктор

2022-08-26 14:23 UTC, blekkiw commented on src/main/java/ninth/ArrayExtendable.java
> +        if ((index >= 0) & (index < this.size)) {
Тут точно нет ошибки с &? Если тебе надо **_И_**, ты должен использовать &&

2022-08-26 14:23 UTC, blekkiw commented on src/main/java/ninth/ArrayExtendable.java
> +        if ((index < 0) & (index > (this.size - 1))) {
Тоже видимо ошибка с &. Если попытаться удалить элемент из пустого массива по индексу, кидает java.lang.NegativeArraySizeException

2022-08-26 14:23 UTC, blekkiw commented on src/main/java/ninth/ArrayExtendable.java
> +    public int getIndex(Measureable objectToFind) {
Этого метода нет в интерфейсе. Ты точно хочешь его показывать "наружу"?

2022-08-26 14:23 UTC, blekkiw commented on src/main/java/ninth/ArrayExtendable.java
> +        } else return;
Можно вообще не писать тут return, все равно метод завершится и ниже ничего нету

2022-08-26 14:23 UTC, blekkiw commented on src/main/java/ninth/ArrayExtendable.java
> +    public int length() {
Может стоит сделать приватным?

2022-08-26 14:23 UTC, blekkiw commented on src/main/java/ninth/MeasurableList.java
> +public interface MeasurableList {
Добавь у кслассов с имплементацией над методами @ Override

2022-08-26 14:23 UTC, blekkiw commented on src/main/java/ninth/ListLinked.java
> +    public void remove(int index) {
Если попытаться удалить элемент с несуществующим индексом, кидает java.lang.NullPointerException

2022-08-27 05:34 UTC, tru10b commented on src/main/java/ninth/ArrayExtendable.java
> +    public int getIndex(Measureable objectToFind) {
сделал приватным

2022-08-27 05:36 UTC, tru10b commented on src/main/java/ninth/ArrayExtendable.java
> +    public int length() {
этот метод сделан как раз чтобы можно было снаружи посмотреть размер массива
в самом классе он не применяется
поэтому он публичный

2022-08-27 05:36 UTC, tru10b commented on src/main/java/ninth/MeasurableList.java
> +public interface MeasurableList {
исправил

2022-08-27 05:37 UTC, tru10b commented on src/main/java/ninth/IntArrayUtils.java
> +
добавил

2022-08-27 05:52 UTC, tru10b commented on src/main/java/ninth/ArrayExtendable.java
> +        if ((index >= 0) & (index < this.size)) {
исправил

2022-08-27 05:53 UTC, tru10b commented on src/main/java/ninth/ArrayExtendable.java
> +        } else return;
убрал

2022-08-27 06:33 UTC, tru10b commented on src/main/java/ninth/ArrayExtendable.java
> +        if ((index < 0) & (index > (this.size - 1))) {
fixed

2022-08-27 07:56 UTC, tru10b commented on src/main/java/ninth/ListLinked.java
> +    public void remove(int index) {
fixed

2022-08-27 17:32 UTC, blekkiw requested changes

2022-08-27 17:32 UTC, blekkiw commented on src/main/java/ninth/ArrayExtendable.java
> +    private int size = 0;
А зачем вообще нужен size если можно у самого массива узнать length?

2022-08-27 17:32 UTC, blekkiw commented on src/main/java/ninth/ArrayExtendable.java
> +    public int length() {
Если у тебя оба листа умеют это делать, добавь это в интерфейс

2022-08-27 17:32 UTC, blekkiw commented on src/main/java/ninth/ListLinked.java
> +        if (((index < 0) || (index > sizeOfList)) || (headOfList.nodeValue == null)) {
Кажется со скобками переборщил

2022-08-27 18:29 UTC, tru10b commented on src/main/java/ninth/ArrayExtendable.java
> +    public int length() {
добавил

2022-08-27 18:30 UTC, tru10b commented on src/main/java/ninth/ArrayExtendable.java
> +    private int size = 0;
излишне, убрал

2022-08-27 18:45 UTC, tru10b commented on src/main/java/ninth/ListLinked.java
> +        if (((index < 0) || (index > sizeOfList)) || (headOfList.nodeValue == null)) {
исправил везде

2022-08-31 11:14 UTC, blekkiw requested changes

2022-08-31 11:14 UTC, blekkiw commented on src/main/java/ninth/ArrayExtendable.java
> +        return this.current.length;
Да, только ты инитишь массив нуллом, а занчит тут будет null pointer, если ты не добавил ни одного элемента. Сделай проверку, и если массив == нулл, возвращай 0

2022-09-05 16:30 UTC, tru10b commented on src/main/java/ninth/ArrayExtendable.java
> +        return this.current.length;
fixed

2022-09-11 15:43 UTC, merged