*new package eleventh + add method for access to private fields in cl…
FreeCourseJava/FFF_homeworks pull request #7
Opened 2022-09-12 16:31 UTC by tru10b

…asses Measureable and House

2022-09-28 05:26 UTC, hyragano requested changes

2022-09-28 05:26 UTC, hyragano commented on src/main/java/twelfth/DictionaryLinkedList.java
> +            if (temp.key == key) {
Разве по == нужно в данном кейсе сравнивать объекты?

2022-09-28 05:26 UTC, hyragano commented on src/main/java/twelfth/DictionaryHashTable.java
> +        int hash = key.toString().hashCode();
Hashcode тоже есть у всех объектах. У класса может быть не переопределен toString, но переопределен Hashcode и  equals.
Более того: у toString только информативное применение, а тут на него завязывается поведение структуры.

2022-10-02 19:33 UTC, tru10b commented on src/main/java/twelfth/DictionaryLinkedList.java
> +            if (temp.key == key) {
исправил

2022-10-02 19:35 UTC, tru10b commented on src/main/java/twelfth/DictionaryHashTable.java
> +        int hash = key.toString().hashCode();
переопределил equals и hashCode, однако все равно хочу хэшкод считать как хэшкод строки, составленной из значимых частей строки

2022-10-04 06:25 UTC, blekkiw approved these changes

2022-10-12 20:21 UTC, blekkiw approved these changes

2022-10-13 19:47 UTC, merged