*new package 14
FreeCourseJava/FFF_homeworks pull request #8
Opened 2022-10-17 16:33 UTC by tru10b

Binary Tree Dictionary homework

2022-10-17 17:04 UTC, dmitriigo requested changes

2022-10-17 17:04 UTC, dmitriigo commented on src/main/java/fourteenth/BinaryDictionary.java
> +        } while (true);
Лучше никогда не использовать while (true). Нужно всегда оставлять возможность выхода из цикла. Без break, return

2022-10-17 17:04 UTC, dmitriigo commented on src/main/java/fourteenth/BinaryDictionary.java
> +        int hashKey = key.hashCode();
Если ключ будет null, будет NPE

2022-10-17 17:04 UTC, dmitriigo commented on src/main/java/fourteenth/BinaryDictionary.java
> +        int hashKey = key.hashCode();
Если key будет null, будет  NPE. Одно из решений - для null ключей, ставить хэшкод равным 0

2022-10-17 17:04 UTC, dmitriigo commented on src/main/java/fourteenth/BinaryDictionary.java
> +        do {
Лучше вместо do-while использовать for по коллекции. Он более читаемый

2022-10-17 20:09 UTC, tru10b commented on src/main/java/fourteenth/BinaryDictionary.java
> +        int hashKey = key.hashCode();
исправил

2022-10-17 20:09 UTC, tru10b commented on src/main/java/fourteenth/BinaryDictionary.java
> +        int hashKey = key.hashCode();
исправил

2022-10-17 20:48 UTC, tru10b commented on src/main/java/fourteenth/BinaryDictionary.java
> +        } while (true);
согласен. переписал метод гет, но для пута не знаю как переписать пока
можно было бы через фор организовать, если дополнительно ввести для дерева счетчик узлов

2022-10-17 20:51 UTC, tru10b commented on src/main/java/fourteenth/BinaryDictionary.java
> +        do {
я так понимаю это только для настоящей коллекции можно, а для самопальной структуры только через итераторные методы перебор делаецца

2022-10-18 16:24 UTC, tru10b commented on src/main/java/fourteenth/BinaryDictionary.java
> +        do {
пробовал через форич переписать циклы, но я криво реализовал итератор
он только тасует значения в узлах, а видимо надо чтобы узлы полностьью тасовал

2022-10-19 08:15 UTC, tru10b commented on src/main/java/fourteenth/BinaryDictionary.java
> +        do {
Разобрался, исправил

2022-10-19 08:48 UTC, tru10b commented on src/main/java/fourteenth/BinaryDictionary.java
> +        } while (true);
исправил

2022-10-19 08:57 UTC, blekkiw approved these changes

2022-10-22 19:52 UTC, merged